### ISSUE TITLE
Issues installing treesitter parsers on MacOS using clang.

### ISSUE THREAD

**Issue by connorgmeehan** [NTBBloodbath/doom-nvim#246]
Many treesitter parsers are not compatible with the `clang` compiler supplied with Xcode.  To solve this you will need to run nvim using gcc when installing the parsers.

### Temporary solution (start neovim using gcc one time)
1. First install gcc using homebrew
`brew install gcc`
2. Run this one liner:
`CC=$(brew unlink --dry-run gcc | grep "$(brew --prefix)/bin" | grep "\/gcc-\d\d"| head -n 1) nvim`
3. (Optional) uninstall gcc, (you wont need it anymore unless you want to install more treesitter languages/parsers)
`brew uninstall gcc`

### Permanent solution (always use gcc when running neovim)
1. First install gcc using homebrew
`brew install gcc`
2. Find path to gcc executable
`brew unlink --dry-run gcc | grep "$(brew --prefix)/bin" | grep "\/gcc-\d\d"`
2. Create an alias to nvim that uses the path to gcc executable for `CC`, add this to your `~/.zshrc` or `~/.bashrc` file and be sure to replace the path.
`alias nvim="CC=/usr/local/bin/gcc-11 nvim"` 

---
> This is a copy of #222, I'm creating this issue so we can direct users to an easy to find solution.  Please close it when you have time @NTBBloodbath :)
> WARNING: This solution will only work on doom-nvim v3.2 and greater (solved by #247 ).  Check what version you have with `:DoomInfo`

**Comment by molleweide** [comment]
this is great! I learnt a lot from reading this!

**Comment by laermannjan** [comment]
I followed the steps above but I am still running into right after 
> `CC=$(brew unlink --dry-run gcc | grep "$(brew --prefix)/bin" | grep "\/gcc-\d\d"| head -n 1) nvim`

```bash
nvim-treesitter[lua]: Error during compilation
In file included from /usr/local/Cellar/gcc/11.2.0_3/lib/gcc/11/gcc/x86_64-apple-darwin21/11/include/stdint.h:9,
                 from ./src/tree_sitter/parser.h:9,
                 from src/parser.c:1:
/usr/local/Cellar/gcc/11.2.0_3/lib/gcc/11/gcc/x86_64-apple-darwin21/11/include-fixed/stdint.h:27:10: fatal error: sys/_types/_int8_t.h: No such file or directory
   27 | #include <sys/_types/_int8_t.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/local/Cellar/gcc/11.2.0_3/lib/gcc/11/gcc/x86_64-apple-darwin21/11/include/stdint.h:9,
                 from ./src/tree_sitter/parser.h:9,
                 from src/scanner.cc:1:
/usr/local/Cellar/gcc/11.2.0_3/lib/gcc/11/gcc/x86_64-apple-darwin21/11/include-fixed/stdint.h:27:10: fatal error: sys/_types/_int8_t.h: No such file or directory
   27 | #include <sys/_types/_int8_t.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I am running MacOS Monterey, nvim 0.6.0 and tried both the `stable` and `develop`.
Any ideas why this still persists?

**Comment by connorgmeehan** [comment]
Interesting, it seems to be a more general error with GCC.  Did you recently update to Monterey?  Did you install `gcc` before updating?  I found [this](https://stackoverflow.com/questions/52599779/macos-fatal-error-sys-types-int8-t-h-no-such-file-or-directory-include-sys) stack overflow post that says that GCC may need to be re-installed after updating MacOS versions.

**Comment by laermannjan** [comment]
Yes, I did upgrade recently and had a completely setup system before.

I've seen that post before, but didn't think reinstalling homebrew was actually necessary (and really wanted to avoid this).
I tried reinstalling `gcc`, which didn't work.

Now I actually did reinstall homebrew and it **does** work now!

A bit annoying, as you have to reinstall everything installed through brew as well.
For everyone else reaching this, don't forget to save your casks and formulae:

```bash
brew leaves -r > homebrew-formulae.txt
brew list --cask > homebrew-cask.txt

# reinstall brew
# ...
# 

brew install `cat homebrew-formulae.txt`
brew install --cask `cat homebrew-casks.txt`
```

Thanks for having a look.

**Comment by molleweide** [comment]
compiling `norg` has stopped working for me now also on macOS big Sur on M1 macbook. I have too think about whether I should reinstall brew now myself also.

**Comment by rdkohalmy** [comment]
The alias fix was not working for me. I did some digging and what I cam up with is:

`alias vim="CC=/opt/homebrew/Cellar/gcc/11.2.0_3/bin/gcc-11 nvim"`

This is with Doom Nvim 3.3.0 and macOS 12.3 21E230 arm64

Hope this can help someone in the future running into the same issue. 👍

**Comment by mchisolm0** [comment]
When I set the alias for the permanent method, I get the error that the function nvim immediately calls itself which would lead to an infinite loop. I went ahead and did the 1 liner, and it is working now. Why is the the alias method failing?

Useful info:
shell: fish
Output of `brew unlink...`: /usr/local/bin/gcc-12
alias nvim="CC=/usr/local/bin/gcc-12 nvim"

**Comment by molleweide** [comment]
> When I set the alias for the permanent method, I get the error that the function nvim immediately calls itself which would lead to an infinite loop. I went ahead and did the 1 liner, and it is working now. Why is the the alias method failing?
> 
> Useful info: shell: fish Output of `brew unlink...`: /usr/local/bin/gcc-12 alias nvim="CC=/usr/local/bin/gcc-12 nvim"

I did the same with `CC=/usr/local/bin/gcc nbim` and it also worked.

**Comment by molleweide** [comment]
For anyone reading, make sure to update brew to latest version with `brew upgrade`.
